### ISSUE TITLE
Osmium Ore not in ore generation

### ISSUE THREAD

**Issue by Wyattsb** [KazroFox/KazPack#12]
Osmium Ore not in ore generation, going to retroactively generate on current map, but needs to be enabled in configs for client and server

**Comment by Wyattsb** [comment]
Created an osmium ore.json in cofh/world and turned on retrogen, will turn off later tonight, but it at least exists now.

**Comment by KazroFox** [comment]
If it's the Retrogen setting from CoFHCore, it disables itself after it runs once as far as I know.

**Comment by Wyattsb** [comment]
This goes into {root}/config/cofh/world/*.json
[Mekanism-Ores.zip](https://github.com/KazroFox/KazPack/files/285566/Mekanism-Ores.zip)
